urdf: simplified_movo.urdf
link_radius: 0.05 
base_links:
  - base_link
  - base_link
ee_links:
  - right_ee_link
  - left_ee_link
starting_config: [0.1, -1.5, -0.2, -1.0, -2.0, 2.0, -1.2354, -1.1, 0.1, 1.5, 0.2, 1.0, 2.0, -2.0, 1.2354, 1.1]
obstacles:
  cuboids:
    - name: box1
      scale: [0.35,0.6,0.002]
      translation: [0.6,0.0,0.0]
      rotation: [0.0,0.0,0.0]
      animation: static
