urdf: simplified_movo.urdf
link_radius: 0.05 
base_links:
  - base_link
  - base_link
ee_links:
  - right_ee_link
  - left_ee_link
starting_config: [0.35, -1.5, -0.2, -1.0, -2.0, 2.0, -1.2354, -1.1, 1.5, 0.2, 1.0, 2.0, -2.0, 1.2354, 1.1]
chains_def: [[0,1,2,3,4,5,6,7],[0,8,9,10,11,12,13,14]]
obstacles:
  cuboids:
    - name: box1
      scale: [0.35,0.6,0.002]
      translation: [0.6,0.0,0.0]
      rotation: [0.0,0.0,0.0]
      animation: static
    - name: sphere2
      scale: [0.15, 0.15, 0.15]
      translation: [1.0,0.0,0.8]
      rotation: [0.0,0.0,0.0]
      animation: static
