urdf: simplified_movo_fixedfingers.urdf
link_radius: 0.05 
base_links:
  - base_link
  - base_link
  - base_link

ee_links:
  - right_gripper_finger1_finger_tip_link
  - right_gripper_finger2_finger_tip_link
  - right_gripper_finger3_finger_tip_link



# starting_config:   [0.35, -1.5, -0.2, -0.0, -2.0, 2.0, -1.2354, -1.1]

# chains_def: [[0,1,2,3,4,5,6,7,8],[0,1,2,3,4,5,6,7,9],[0,1,2,3,4,5,6,7,10]]
starting_config:   [0.35, -1.5, -0.2, -0.0, -2.0, 2.0, -1.2354, -1.1,0.5,0.5,0.5]

chains_def: [[0,1,2,3,4,5,6,7,8],[0,1,2,3,4,5,6,7,9],[0,1,2,3,4,5,6,7,10]]

# Add Environment Obstacles
obstacles:
  cuboids:
    - name: table
      scale: [0.275,0.6,0.24]
      translation: [0.8,0.0,0.24]
      rotation: [0.0,0.0,0.0]
      animation: static
  point_cloud:
    # - name: bunny
    #   scale: [2.0,2.0,2.0]
    #   translation: [1.0,-0.5,0.9]
    #   rotation: [1.57,0.0,-1.57]
    #   animation: static
    #   file: bunny


# For trajectory tracing
# traj_files: [traject_6d_5_right.npy, traject_6d_5_left.npy]

# traj_files: [traject_6d_1.npy]